# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  pull_request:
    branches: [ master ]

env:
  NX_BRANCH: ""
  NX_RUN_GROUP: ""

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Cache
        uses: actions/cache@v2.1.1
        with:
          path: |
            ~/cache
            !~/cache/exclude
            **/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}
      # Yarn action
      - name: GitHub Action for Yarn
        uses: Borales/actions-yarn@v2.3.0
        with:
          cmd: install

      # Show env. variables
      - name: See env. variables NX_BRANCH
        run: echo "::set-env name=NX_BRANCH::$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")"
      - name: See env. variables NX_RUN_GROUP
        run: echo "::set-env name=NX_RUN_GROUP::$GITHUB_RUN_NUMBER"

      # Runs a single command using the runners shell
      - name: Nx command build
        run: yarn nx build sample --scan
      - name: Nx command lint
        run: yarn nx lint sample --scan
      - name: Nx command test
        run: yarn nx test sample --scan
